patterns:
  credentials: "\\b(парол[ей]+|логин[а-я]*|аккаунт|account)\\b"
  personal: "\\b(паспорт|снилс|телефон|адрес|email)\\b"
  financial: "\\b(карт[а-я]+|счет[а-я]*|банк[а-я]*)\\b"
  health: "\\b(медицинск[а-я]+|диагноз|медикамент)\\b"
  intellectual_property: "\\b(патент|торговая марка|искусство|код)\\b"
  volume: "\\b\\d{1,3}([\\s,]\\d{3})*(\\.|,)?\\d*\\s?(GB|MB|TB|тыс\\.|млн\\.|запися[йи])\\b"
  leak: "\\b(утечк[а-я]+|слив|кража|компрометация)\\b"

whitelist:
  - "пример.*логина"
  - "вставьте.*телефон"
  - "ваш.*email.*здесь"

delay_range: [4, 8]  # Задержка между запросами в секундах

results_dir: "~/pastebin_results"

threads: 5
