keywords:
  - утечка данных
  - утекшие пароли
  - слив персональных данных
  - база пользователей

site_filters:
  - site:ru
  - site:рф

target_domains:
  - ru
  - рф

search:
  results_per_query: 10
  delay_range: [1, 3]  # пауза между запросами в секундах

analysis:
  required_triggers:
    - leak

storage:
  processed_file: /VKR/diplom/web_parser/web_parser_result/processed.json
  results_file: /VKR/diplom/web_parser/web_parser_result/leaks.json

crawling:
  timeout: 10
  delay_range: [1, 3]
  threads: 5  # количество параллельных потоков

user_agents:
  - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15
  - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
